# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
    - repo: https://github.com/psf/black
      rev: 23.3.0
      hooks:
        # - id: black
        - id: black-jupyter
    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
        - id: isort
          name: isort (python)
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.3.1
      hooks:
        - id: pyupgrade
          args: [--py311-plus]
    - repo: https://github.com/nbQA-dev/nbQA
      rev: 1.7.0
      hooks:
        - id: nbqa-isort
        - id: nbqa-black
        - id: nbqa-pyupgrade
          args: [--py311-plus]
default_language_version:
    python: python3.11
